apiVersion: v1
kind: PersistentVolume
metadata:
  name: accounts-db-pv
  namespace: accounts
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: standard
  hostPath:
    path: /data/postgresql
